### PR TITLE
Standardize fields layout

### PR DESCRIPTION
**Pull request by Zasco**
Use "_form-floating_" style for all fields.

### CODE REVIEW

**Comment by noah-severyn** [comment]
Parts of this are bit broken → https://imgur.com/Lf9aonO

I'm also not a huge fan of resizing the text boxes to be all the same size. I'll work on this a bit more myself.

**Comment by Zasco** [comment]
> Parts of this are bit broken → https://imgur.com/Lf9aonO

This is meant to be handled by [these changes](https://github.com/noah-severyn/SC4PackMan/pull/23/files#diff-a3395c619d2932c6a78cdd9a018c00daf39c06c44622de8726964591322f3e7eR71). Tested on _Firefox_ **115.15.0esr**.

**Comment by noah-severyn** [comment]
> > Parts of this are bit broken → https://imgur.com/Lf9aonO
> 
> This is meant to be handled by [these changes](https://github.com/noah-severyn/SC4PackMan/pull/23/files#diff-a3395c619d2932c6a78cdd9a018c00daf39c06c44622de8726964591322f3e7eR71). Tested on _Firefox_ **115.15.0esr**.

Ah ok thanks, I must have missed that. I wanted to redesign how adding dependencies worked slightly from a UI perspective, so please let me know what you think about the current site.

**Comment by Zasco** [comment]
> Ah ok thanks, I must have missed that. I wanted to redesign how adding dependencies worked slightly from a UI perspective, so please let me know what you think about the current site.


I think the dependency selectors are too narrow. #45 might be the solution. Also, I prefer the "_form-floating_" style to the "_group-input_" because the fields are wider this way.

**Pull request closed without merging**
